<!DOCTYPE html>
<html>
<head>
    <title>KUBEjs Core: KUBE.Promise()</title>
    <!-- Include KUBE.js -->
    <script src="../../../src/KUBE.js"></script>

    <!-- KUBE.Is is a part of KUBE.js and therefore does not require loading -->
    <script type="text/javascript">

        /*
         *  KUBE.Promise is a fairly standard promise library. It was a late addition to KUBEjs so has not been heavily used, and is still slightly incomplete
         *  KUBE.Promise takes an executor callback and returns a promise object with then/catch
         *
         *  API includes: (lowercase is how it is traditionally done, upper case is the KUBE style for public methods)
         *      -then/Then
         *      -catch/Catch
         *
         *  The API also includes some other standard promise methods like:
         *      -resolve
         *      -reject
         *      -all
         *      -race
         *
         *  These methods can not be called with an executor function (aka: KUBE.Promise(function(res,rej){res(3)}).resolve(12)
         *  If this is attempted, an error will be thrown.
         *
         */

        //1
        var KPromise = KUBE.Promise(function(_resolve,_reject){
           //Do async stuff. When done, call _resolve to fire the next resolution callback, or _reject to fire the next reject callback
            setTimeout(function(){
                _resolve('we initially resolve after a half second')
            },500);
        });

        //2
        KPromise.then(function(_data){
            //Then also returns a Promise Obj
            //To resolve, simply return a value (in this case, as we are creating a new async action, we must create a new promise to return)
            //To reject, throw an error (or reject with an error in the case of returning a new promise);
            console.log(_data);
            //If we need to do another asynchronous task, we must return (resolve with) a new promise.
            return KUBE.Promise(function(_resolve,_reject){
                setTimeout(function(){
                    var E = new Error('we then reject after a half second');
                    _reject(E); //If data passed into reject is not an Error object, it is attached to an error object inside of client
                },500);
            });
        });

        //3
        KPromise.catch(function(_Error){
            //Catch also returns a Promise Obj
            console.log(_Error.message);
            //We can resolve the error (or throw the error) to continue this chain as well.
            return 'we can continue the chain even in a rejection';
        });

        //4
        //Then will accept a resolve/reject callback as first/second arg. In this case, only one of the functions will be called, before the chain moves on
        KPromise.then(
            function(_data){
                console.log(_data);
                //Also if an error is throw inside of the promise chain, it automatically calls the next rejection
                throw new Error('This is an error being thrown');
            },
            function(_Error){
                //This won't be called because we resolved 3
            }
        );

        KPromise.catch(function(_Error){
            console.log(_Error.message);
            console.log('We will resolve now but put a delay between this and even binding the next then');
            return 'We resolved';
        });

        //5
        //Even though a chain is resolved, this puts it in a state ready to fire. This means an additional 'then' will automatically get fired and start the chain up again
        setTimeout(function(){
            KPromise.then(function(){
                console.log('The chain has been started again');
                return true;
            });
        },2000);
    </script>

</head>
<body>
View Page Source for Example - Data outputs to console
</body>
</html>